# Travis CI
language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0

before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild
  - chmod a+x script/test
script: script/cibuild

sudo: false
cache: bundler

notifications:
  email: false

matrix:
  fast_finish: true
